# Assignment 4 - Supervised Learning
#### Due Monday, November 12 2018

Submission: Put the data and Jupyter notebook files in a folder. Make sure all links to data are relative to the folder so the TAs can run the notebooks. Points will be deducted if the TAs can't run the notebooks.

Use the public dataset that you used for cleaning in the EDA assignment OR you can use the datset that you are using for your project. You MUST get approval if you wish to use a different dataset.

In this assingment you will compare various forms of supervised learning. You will also create a stacked ensemble super-learner.


In [1]:
# Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
import mpl_toolkits
import seaborn as sns

# Selecting cleaned file
data = pd.read_csv('cleanfile.csv')

In [2]:
# Checking for if file is cleaned
data.shape

(9382, 17)

In [3]:
data.head(5)

Unnamed: 0      Suburb          Address  Rooms Type      Price  Postcode  \
0           2  Abbotsford  25 Bloomburg St      2    h  1035000.0    3067.0   
1           4  Abbotsford     5 Charles St      3    h  1465000.0    3067.0   
2           6  Abbotsford      55a Park St      4    h  1600000.0    3067.0   
3          11  Abbotsford     124 Yarra St      3    h  1876000.0    3067.0   
4          14  Abbotsford    98 Charles St      2    h  1636000.0    3067.0   

   Bedroom2  Bathroom  Car  Landsize  BuildingArea YearBuilt  \
0       2.0       1.0  0.0     156.0          79.0    1900.0   
1       3.0       2.0  0.0     134.0         150.0    1900.0   
2       3.0       1.0  2.0     120.0         142.0    2014.0   
3       4.0       2.0  0.0     245.0         210.0    1910.0   
4       2.0       1.0  2.0     256.0         107.0    1890.0   

          CouncilArea Lattitude Longtitude             Regionname  
0  Yarra City Council  -37.8079   144.9934  Northern Metropolitan  
1  Yarra City Council  -37.8093   144.9944  Northern Metropolitan  
2  Yarra City Council  -37.8072   144.9941  Northern Metropolitan  
3  Yarra City Council  -37.8024   144.9993  Northern Metropolitan  
4  Yarra City Council   -37.806   144.9954  Northern Metropolitan

In [4]:
data.tail(5)

Unnamed: 0      Suburb           Address  Rooms Type      Price  \
9377       34847     Wollert   27 Birchmore Rd      3    h   500000.0   
9378       34849     Wollert   35 Kingscote Wy      3    h   570000.0   
9379       34853  Yarraville     29A Murray St      2    h   888000.0   
9380       34854  Yarraville    147A Severn St      2    t   705000.0   
9381       34856  Yarraville  3 Tarrengower St      2    h  1020000.0   

      Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea YearBuilt  \
9377    3750.0       3.0       2.0  2.0     383.0         118.0    2016.0   
9378    3750.0       3.0       2.0  2.0     404.0         158.0    2012.0   
9379    3013.0       2.0       2.0  1.0      98.0         104.0    2018.0   
9380    3013.0       2.0       1.0  2.0     220.0         120.0    2000.0   
9381    3013.0       2.0       1.0  0.0     250.0         103.0    1930.0   

                   CouncilArea            Lattitude          Longtitude  \
9377   Whittlesea City Council             -37.6194           145.03951   
9378   Whittlesea City Council            -37.61031           145.03393   
9379  Maribyrnong City Council  -37.815509999999996           144.88826   
9380  Maribyrnong City Council            -37.82286  144.87856000000002   
9381  Maribyrnong City Council             -37.8181  144.89351000000002   

                 Regionname  
9377  Northern Metropolitan  
9378  Northern Metropolitan  
9379   Western Metropolitan  
9380   Western Metropolitan  
9381   Western Metropolitan

In [5]:
data.drop(['Unnamed: 0', 'Regionname'], axis=1, inplace=True)

In [6]:
data.shape

(9382, 15)

### Part A - Supervised learning (50 points)
Supervised learning infers a function from labeled training data consisting of a set of training examples.:
  * Predict a dependent variable using at least four classes of base supervised learners.

Answer the following questions for each supervised learner:
* Which hyper-parameters are important?
* What hyper-parameter values work best? 
* Which supervised learner works best on the test data?  

#### Predicting dependent variable using 4 classes of based supervised learning

#### Linear Regression

In [7]:
# Linear Regression
# Import Library

from __future__ import print_function
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, AdaBoostRegressor

from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.cross_validation import train_test_split
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn.model_selection import KFold
# from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
%matplotlib inline
import pylab as pl


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [8]:
X = data[["Rooms", "Bathroom"]]
y = data[["Price"]]

# Fit the linear model
model = linear_model.LinearRegression()
results = model.fit(X, y)

# Print the coefficients
print (results.intercept_, results.coef_)

# import statsmodels.api as sm
# Swap of X and y
model = sm.OLS(y, X)
results = model.fit()
# Statsmodels gives R-like statistical output
results.summary()

[19617.38092175] [[211572.99654936 255050.8124261 ]]


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.797
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                 1.841e+04
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:39:29   Log-Likelihood:            -1.3782e+05
No. Observations:                9382   AIC:                         2.756e+05
Df Residuals:                    9380   BIC:                         2.757e+05
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms       2.168e+05   5832.997     37.165      0.000    2.05e+05    2.28e+05
Bathroom    2.561e+05   1.05e+04     24.394      0.000    2.36e+05    2.77e+05
==============================================================================
Omnibus:                     4753.006   Durbin-Watson:                   1.402
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            68051.136
Skew:                           2.084   Prob(JB):                         0.00
Kurtosis:                      15.518   Cond. No.                         7.30
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1)
reg_all = linear_model.LinearRegression()
reg_all.fit(X_train, y_train)
y_pred = reg_all.predict(X_test)
reg_all.score(X_test, y_test)

0.2562988910759404

#### Lasso Regression

In [10]:
# Lasso Regression
# Importing Libraries

from __future__ import print_function
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, AdaBoostRegressor


from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.cross_validation import train_test_split
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn.model_selection import KFold
# from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
%matplotlib inline
import pylab as pl

In [11]:
# Lasso regression with an alpha of 5.0
lasso = Lasso(fit_intercept=True, alpha=1.0)
lasso.fit(X_train,y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [12]:
# Predicting the Test set results
y_pred2 = lasso.predict(X_test)

In [13]:
lasso.get_params().keys()

dict_keys(['alpha', 'copy_X', 'fit_intercept', 'max_iter', 'normalize', 'positive', 'precompute', 'random_state', 'selection', 'tol', 'warm_start'])

In [14]:
from sklearn.model_selection import GridSearchCV
params={'alpha': [25,10,4,2,1.0,0.8,0.5,0.3,0.2,0.1,0.05,0.02,0.01]}
grid_lasso = GridSearchCV(lasso,params, cv=2,verbose = 1)
grid_lasso.fit(X_train, y_train)

Fitting 2 folds for each of 13 candidates, totalling 26 fits


[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:    0.1s finished


GridSearchCV(cv=2, error_score='raise',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [25, 10, 4, 2, 1.0, 0.8, 0.5, 0.3, 0.2, 0.1, 0.05, 0.02, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [15]:
print(grid_lasso.best_estimator_)

Lasso(alpha=25, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)


In [16]:
model = sm.OLS(y_pred2, X_test)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.200e+10
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:39:35   Log-Likelihood:                -15683.
No. Observations:                2346   AIC:                         3.137e+04
Df Residuals:                    2344   BIC:                         3.138e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms       2.151e+05      3.736   5.76e+04      0.000    2.15e+05    2.15e+05
Bathroom    2.616e+05      6.743   3.88e+04      0.000    2.62e+05    2.62e+05
==============================================================================
Omnibus:                      429.104   Durbin-Watson:                   1.867
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1905.961
Skew:                           0.814   Prob(JB):                         0.00
Kurtosis:                       7.104   Cond. No.                         7.05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

#### Ridge Regression

In [17]:
# Ridge Regression
# Import Libraries

from __future__ import print_function
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, AdaBoostRegressor


from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.cross_validation import train_test_split
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn.model_selection import KFold
# from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
%matplotlib inline
import pylab as pl

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
# Ridge regression with an alpha of 5.0
ridge = Ridge(fit_intercept=True, alpha=5)
ridge.fit(X_train,y_train)

Ridge(alpha=5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [20]:
y_pred3 = ridge.predict(X_test)

In [21]:
# Using grid search to select best hyper parameter set
ridge.get_params().keys()

dict_keys(['alpha', 'copy_X', 'fit_intercept', 'max_iter', 'normalize', 'random_state', 'solver', 'tol'])

In [22]:
from sklearn.model_selection import GridSearchCV
params={'alpha': [25,10,4,2,1.0,0.8,0.5,0.3,0.2,0.1,0.05,0.02,0.01]}
grid_ridge = GridSearchCV(ridge,params, cv=2,verbose = 1)
grid_ridge.fit(X_train, y_train)

Fitting 2 folds for each of 13 candidates, totalling 26 fits


[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:    0.1s finished


GridSearchCV(cv=2, error_score='raise',
       estimator=Ridge(alpha=5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [25, 10, 4, 2, 1.0, 0.8, 0.5, 0.3, 0.2, 0.1, 0.05, 0.02, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [23]:
print(grid_ridge.best_estimator_)

Ridge(alpha=25, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)


In [24]:
model = sm.OLS(y_pred3, X_test)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.981e+06
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:39:39   Log-Likelihood:                -20224.
No. Observations:                1877   AIC:                         4.045e+04
Df Residuals:                    1875   BIC:                         4.046e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms       2.189e+05    260.045    841.864      0.000    2.18e+05    2.19e+05
Bathroom    2.491e+05    465.390    535.326      0.000    2.48e+05     2.5e+05
==============================================================================
Omnibus:                       37.214   Durbin-Watson:                   1.844
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.783
Skew:                          -0.323   Prob(JB):                     2.30e-09
Kurtosis:                       3.304   Cond. No.                         7.18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [25]:
# Random Forrest
# Import Libraries

from __future__ import print_function
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, AdaBoostRegressor


from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.cross_validation import train_test_split
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn.model_selection import KFold
# from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
%matplotlib inline
import pylab as pl

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [27]:
from sklearn.ensemble import RandomForestRegressor
rfg = RandomForestRegressor(n_estimators = 10, random_state = 0)
rfg.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [28]:
y_pred4 = rfg.predict(X_test)

In [29]:
rfg.get_params().keys()

dict_keys(['bootstrap', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_impurity_split', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])

In [30]:
from sklearn.model_selection import GridSearchCV
param_grid = { "n_estimators" : [10,20,30], "max_features" : ["auto", "sqrt", "log2"], "min_samples_split" : [2,4,8], "bootstrap": [True, False],}

grid_rfg = GridSearchCV(rfg, param_grid, n_jobs=-1, cv=5)
grid_rfg.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [10, 20, 30], 'max_features': ['auto', 'sqrt', 'log2'], 'min_samples_split': [2, 4, 8], 'bootstrap': [True, False]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [31]:
print(grid_rfg.best_estimator_)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=4,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)


In [32]:
model = sm.OLS(y_pred4, X_test)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.993
Model:                            OLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                 1.245e+05
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:39:43   Log-Likelihood:                -24249.
No. Observations:                1877   AIC:                         4.850e+04
Df Residuals:                    1875   BIC:                         4.851e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms       2.215e+05   2219.754     99.774      0.000    2.17e+05    2.26e+05
Bathroom    2.477e+05   3972.594     62.344      0.000     2.4e+05    2.55e+05
==============================================================================
Omnibus:                     1244.454   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            58260.146
Skew:                           2.500   Prob(JB):                         0.00
Kurtosis:                      29.832   Cond. No.                         7.18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

According to the results Lasso & Ridge Regression are the best for this test dataset (Melbourne House Prices). With an R-squared value of 1.000 both regression methods are the best for what is required. 

However, as Lasso Regression uses the absolute value of βj instead of the squared value, it gives a more accurate value and is the very best SUpervised Learning method for this dataset.

### Part B - Neural networks can be used for supervised learning (20 points)
Neural networks can be used for supervised learning:
 * Predict a dependent variable using a feed-forward neural network. (25 points)

Answer the following questions for each supervised learner:
* Which hyper-parameters are important?
* What hyper-parameter values work best? 
* How the the neural network compare to the supervised learners in part A? 

In [33]:
# Neural Network
# MLPClassifier

# Import Libraries

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, AdaBoostRegressor


from sklearn.model_selection import train_test_split, cross_validate
#from sklearn.cross_validation import train_test_split
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn.model_selection import KFold
# from sklearn.cross_validation import KFold, cross_val_score, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
%matplotlib inline
import pylab as pl

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [35]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor(hidden_layer_sizes=(500,3),activation='tanh',alpha=100)
mlp.fit(X_train, y_train['Price'])

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='tanh', alpha=100, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(500, 3), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [36]:
y_pred5 = mlp.predict(X_test)

In [37]:
model = sm.OLS(y_pred5, X_test)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.914
Method:                 Least Squares   F-statistic:                     9990.
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:39:54   Log-Likelihood:                -6845.2
No. Observations:                1877   AIC:                         1.369e+04
Df Residuals:                    1875   BIC:                         1.371e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms          8.3657      0.209     40.085      0.000       7.956       8.775
Bathroom       2.0632      0.373      5.524      0.000       1.331       2.796
==============================================================================
Omnibus:                       37.214   Durbin-Watson:                   1.844
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.784
Skew:                          -0.323   Prob(JB):                     2.30e-09
Kurtosis:                       3.304   Cond. No.                         7.18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### Part C - Stacked ensemble super-model (20 points)
Create a stacked ensemble super-model.
Generate a stacked ensemble super-model for the best learners in parts A & B:
 * Did the stacked ensemble super-model help? (25 points)

Answer the following questions for the stacked ensemble super-model:
* How did to combine the models?  
* Cross-validate the model. How well did it do?   


In [38]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor(hidden_layer_sizes=(500,3),activation='tanh',alpha=100)
mlp.fit(X_train, y_train['Price'])

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='tanh', alpha=100, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(500, 3), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [39]:
#Boosting

In [40]:
regressor = AdaBoostRegressor(base_estimator=None, n_estimators=100, learning_rate=1.0, loss='linear', random_state=None)
regressor.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
         n_estimators=100, random_state=None)

In [41]:
y_pred6 = regressor.predict(X_test)
print(y_pred6)

[1286046.77347752 1176506.98340426 1176506.98340426 ...  755301.84176633
  755301.84176633  755301.84176633]


In [42]:
# import statsmodels.api as sm
# Note the swap of X and y
model = sm.OLS(y_pred6, X_test)
results = model.fit()
# Statsmodels gives R-like statistical output
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.984
Model:                            OLS   Adj. R-squared:                  0.984
Method:                 Least Squares   F-statistic:                 5.805e+04
Date:                Fri, 30 Nov 2018   Prob (F-statistic):               0.00
Time:                        00:40:03   Log-Likelihood:                -25095.
No. Observations:                1877   AIC:                         5.019e+04
Df Residuals:                    1875   BIC:                         5.021e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Rooms        2.83e+05   3484.643     81.223      0.000    2.76e+05     2.9e+05
Bathroom    1.824e+05   6236.309     29.247      0.000     1.7e+05    1.95e+05
==============================================================================
Omnibus:                      631.873   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3918.670
Skew:                           1.438   Prob(JB):                         0.00
Kurtosis:                       9.468   Cond. No.                         7.18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
kf = KFold(n_splits=5)

kf.get_n_splits(X)
print(kf)

KFold(n_splits=5, random_state=None, shuffle=False)


In [44]:
lr = LinearRegression()
lr.fit(X_train, y_train['Price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
y_pred = lr.predict(X_test)

In [46]:
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
rmse

601716.7653613715

In [47]:
# RMSE using 5-fold cross-validation

for train,test in kf.split(X):
    print (train)
    print (test)
    scores = []

[1877 1878 1879 ... 9379 9380 9381]
[   0    1    2 ... 1874 1875 1876]
[   0    1    2 ... 9379 9380 9381]
[1877 1878 1879 ... 3751 3752 3753]
[   0    1    2 ... 9379 9380 9381]
[3754 3755 3756 ... 5627 5628 5629]
[   0    1    2 ... 9379 9380 9381]
[5630 5631 5632 ... 7503 7504 7505]
[   0    1    2 ... 7503 7504 7505]
[7506 7507 7508 ... 9379 9380 9381]


In [48]:
# Testing

for train,test in kf.split(X):
    lr.fit(X_train, y_train)
    scores.append(np.sqrt(metrics.mean_squared_error(y_test, lr.predict(X_test))))

print(scores)

[601716.7653613715, 601716.7653613715, 601716.7653613715, 601716.7653613715, 601716.7653613715]


In [49]:
np.mean(scores)

601716.7653613715

In [50]:
np.median(scores)

601716.7653613715

In [51]:
np.std(scores)

0.0

In [52]:
def show_stats(m, ncv, cv):
    print('Method: %s' %m)
    print('RMSE on no CV training: %.3f' %ncv)
    print('RMSE on 5-fold CV: %.3f' %cv)
    
show_stats('Random Forest Regression', rmse, np.mean(scores))

Method: Random Forest Regression
RMSE on no CV training: 601716.765
RMSE on 5-fold CV: 601716.765
